services:
  web:
    build: .
    volumes:
      - .:/app
      - db-data:/app/storage
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - datadog

  sidekiq:
    build: .
    volumes:
      - .:/app
      - db-data:/app/storage
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - datadog

  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  datadog:
    image: "datadog/agent:latest"
    environment:
      - DD_API_KEY=<5e57a74f17f53b0adde4a9f986876779>
      - DD_SITE=us5.datadoghq.com
      - DD_ENV=development
      - DD_SERVICE=luiza_labs_jsonify
      - DD_VERSION=1.0.0
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

volumes:
  db-data:
  redis: